insert into Category (nameCategory) values ('3 à 6 ans');
insert into Category (nameCategory) values ('6 à 9 ans');
insert into Category (nameCategory) values ('9 à 13 ans');
insert into Category (nameCategory) values ('A partir de 13 ans');
insert into Category (nameCategory) values ('A partir de 15 ans');
insert into Category (nameCategory) values ("comics");
insert into publisher (namePublisher) values ('Le Baron perché');
insert into publisher (namePublisher) values ("L'étagère du bas");
insert into publisher (namePublisher) values ('Didier Jeunesse');
insert into publisher (namePublisher) values ('Ecole Des Loisirs');
insert into book values (1,"Un air de familles","2360800701","Maman et moi, on vit toutes les deux dans la savane. Mes parents m’ont adopté quand j’étais tout petit. Papa et maman sont nés dans deux pays différents. Avec mes deux papas, on va souvent au musée. Nous, on n’a pas d’enfant. Les animaux de ce livre à jouer s’alignent par familles, toutes semblables et toutes différentes. Au lecteur de les distinguer grâce aux indices du texte. Des familles monoparentales aux « tribus », en passant par les familles homoparentales et recomposées, personne n’est laissé de côté ! Un album sensible et tendre pour s’amuser, mais aussi pour apprendre de nos différences.","img/1.png",16,2,"J'ai beaucoup aimé",1,1,1);
insert into book values (2,"La disparition de chou","2955789666","Lola a trois ans et vit avec ses parents. Il y a aussi Chou, son doudou koala. Ces deux-là forment un duo inséparable. Mais, un jour, c'est la catastrophe : Chou est introuvable... Il a disparu ! Lola et ses parents le cherchent partout et mettent des avis de recherche dans toute la ville. Aucune réponse et le temps passe...","img/2.png",14,2,"Livre moyen",0,1,2);
insert into book values (3,"Un arbre merveilleux","2278089706","«  Dans mon jardin se trouve un arbre merveilleux… ». Cet arbre majestueux révèle bien des secrets. Au gré du temps qui passe, il accueille le chat qui vient s’y abriter, les oiseaux qui viennent y nicher, un couple de loirs... Quand revient le printemps, dans son feuillage renaissant, on entend bientôt le murmure de nouveaux occupants... Et si tout recommençait ?","img/3.png",13.50,0,"J'ai beaucoup aimé",1,1,3);
insert into book values (9,"Les trois brigands","2211058515","Il était une fois trois vilains brigands… dont la vie changea totalement le jour où ils rencontrèrent Tiffany, la petite orpheline. De trois méchants elle en fit…des bienfaiteurs de l'humanité.","img/9.png",5,8,"Un classique paru pour la première fois en 1968 et toujours autant d’actualité. Une histoire à la lecture accessible et au message toujours autant d’actualité : tout le monde peut s’améliorer.",1,2,4);
insert into author values (1,"Boutignon","Béatrice");
insert into author values (2,"Demasse Pottier","Stéphanie");
insert into author values (3,"Perrotin","Elodie");
insert into author values (4,"Grenier","Delphine");
insert into author values (5,"Tomi","Ungerer");
insert into written value (1,1);
insert into written value (2,2);
insert into written value (3,2);
insert into written value (4,3);
insert into written value (5,9);
insert into users (idUser, nameUser, fNameUser, password, email) value (1,"Falcone", "Thomas", "thomas", "t@t.com");
